backend:
  name: github
  repo: manleyac/manleywebdev2.0

media_folder: static/images
public_folder: /images

collections:
  - name: blog
    label: Blog
    folder: src/cms/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title, widget: string }
      - { label: Image, name: image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    folder: src/cms/projects
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { label: "featured image", name: featuredImage, widget: image }
      - { name: body, label: Body, widget: markdown }
      - { name: deploy, label: Deployed, widget: string }
      - { name: repo, label: Repo, widget: string }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Display Order",
          name: "order",
          widget: "number",
          valueType: "int",
        }